### ISSUE TITLE
Unit testing: implement unit tests (at least 2 test classes and 20 test methods).

### ISSUE THREAD

**Issue by annprzy** [jkarolczak/building-info#24]

**Comment by jkarolczak** [comment]
Added 3 test classes, in total 22 test methods:
:heavy_check_mark : 10 test methods for testing class `Room` 
:heavy_check_mark :  6 test methods for testing class `Location` (including 6 methods using mock objects)
:heavy_check_mark : 6 test methods for testing class `Building` (including 6 methods using mock objects)
